// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WuppertalMapMvc.Data;

#nullable disable

namespace WuppertalMapMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250422105735_AddStopConnection")]
    partial class AddStopConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("WuppertalMapMvc.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Lines")
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("WuppertalMapMvc.Models.StopConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromStopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToStopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromStopId");

                    b.HasIndex("ToStopId");

                    b.ToTable("StopConnections");
                });

            modelBuilder.Entity("WuppertalMapMvc.Models.StopConnection", b =>
                {
                    b.HasOne("WuppertalMapMvc.Models.Stop", "FromStop")
                        .WithMany()
                        .HasForeignKey("FromStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WuppertalMapMvc.Models.Stop", "ToStop")
                        .WithMany()
                        .HasForeignKey("ToStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStop");

                    b.Navigation("ToStop");
                });
#pragma warning restore 612, 618
        }
    }
}
